#####################################################################################
# SHINY APP FOR TILE PLOT WITH INTERACTIVE TPR/FPR THRESHOLDS
#
# Theresa Ullmann, Daniela Dunkler
# May 2026
#
#####################################################################################

library(shiny)
library(pROC)
library(reshape2)
library(ggplot2)
library(dplyr)
library(ggrepel)
library(patchwork)
library(cowplot)
library(grid)

# Load pre-computed TPR/FPR and model size data (generated by preprocess_tiles.R).
# This runs ONCE at app startup Slider updates only re-apply threshold logic.
load("precomputed_tiles.RData")  # loads: precomp_log03, precomp_log005, precomp_lin

methods <- c("FU", "FSel_AIC", "Step_FSel_AIC", "ABE_AIC", "BE_BIC", "BE_005",
             "BE_AIC", "BE_05", "Lasso", "RLasso", "RLasso_BIC", "AdaLasso")

# core tile-building function (uses pre-computed TPR/FPR & model size)
# methods_subset: optional character vector restricting which methods are shown.
#   When NULL (default) all 8 methods are displayed; pass a subset for narrow plots.
create_tiles <- function(precomp,
                         TPR_mild_group, FPR_mild_group,
                         TPR_medium_group, FPR_medium_group,
                         TPR_strict_group, FPR_strict_group,
                         methods_subset = NULL) {
  
  EPV   <- precomp$EPV
  title <- precomp$title
  # Round EPV values for display labels
  epv_labels <- round(as.numeric(as.character(EPV)))
  
  # Pre-computed data,  o file I/O or heavy computation here
  res_long_TPR_FPR   <- precomp$TPR_FPR       # list("strong"=..., "weak"=...)
  res_long_model_size <- precomp$model_size    # list("strong"=..., "weak"=...)
  
  df <- data.frame(Var2 = character(), crit_fulfilled = character(),
                   L1 = character(), signal = character(), modelsize = numeric())
  
  for (i in 1:2) {
    sig      <- c("strong", "weak")[i]
    tpr_fpr  <- res_long_TPR_FPR[[sig]] %>% rename(noise = pred)
    msize    <- res_long_model_size[[sig]]
    
    for (method in c("BE_05", "Lasso")) {
      df <- rbind(df,
                  tpr_fpr %>% filter(L1 == method) %>%
                    group_by(Var2) %>%
                    summarise(
                      crit_fulfilled = ifelse(
                        all(value[noise == FALSE] >= TPR_mild_group) &
                          all(value[noise == TRUE]  <= FPR_mild_group), "green", "red"),
                      .groups = "drop"
                    ) %>%
                    mutate(L1 = method, signal = sig) %>%
                    left_join(msize, by = c("Var2", "L1"))
      )
    }
    
    for (method in c("BE_AIC", "RLasso", "AdaLasso")) {
      df <- rbind(df,
                  tpr_fpr %>% filter(L1 == method) %>%
                    group_by(Var2) %>%
                    summarise(
                      crit_fulfilled = ifelse(
                        all(value[noise == FALSE] >= TPR_medium_group) &
                          all(value[noise == TRUE] <= FPR_medium_group), "green", "red"),
                      .groups = "drop"
                    ) %>%
                    mutate(L1 = method, signal = sig) %>%
                    left_join(msize, by = c("Var2", "L1"))
      )
    }
    
    for (method in c("BE_BIC", "BE_005", "RLasso_BIC")) {
      df <- rbind(df,
                  tpr_fpr %>% filter(L1 == method) %>%
                    group_by(Var2) %>%
                    summarise(
                      crit_fulfilled = ifelse(
                        all(value[noise == FALSE] >= TPR_strict_group) &
                          all(value[noise == TRUE]  <= FPR_strict_group), "green", "red"),
                      .groups = "drop"
                    ) %>%
                    mutate(L1 = method, signal = sig) %>%
                    left_join(msize, by = c("Var2", "L1"))
      )
    }
  }
  
  df$EPV <- df$Var2
  levels(df$EPV) <- EPV
  
  # Determine which methods to display; filter data accordingly
  method_levels_full <- c("Lasso", "BE_05", "BE_AIC", "AdaLasso", "RLasso",
                          "BE_005", "BE_BIC", "RLasso_BIC")
  method_levels <- if (!is.null(methods_subset)) methods_subset else method_levels_full
  df <- df %>% filter(L1 %in% method_levels)
  method_labels <- c(
    "BE_05"      = "BE(0.50)",
    "Lasso"      = "Lasso(CV)",
    "BE_AIC"     = "BE(AIC)",
    "RLasso"     = "RLasso(CV)",
    "AdaLasso"   = "AdaLasso(CV)",
    "BE_BIC"     = "BE(BIC)",
    "BE_005"     = "BE(0.05)",
    "RLasso_BIC" = "RLasso(BIC)"
  )
  facet_bg_colors <- c(
    "BE_05"      = "#e6f2ff",
    "Lasso"      = "#e6f2ff",
    "BE_AIC"     = "#fff5e6",
    "RLasso"     = "#fff5e6",
    "AdaLasso"   = "#fff5e6",
    "BE_BIC"     = "#f2e6ff",
    "BE_005"     = "#f2e6ff",
    "RLasso_BIC" = "#f2e6ff"
  )
  
  df_plot <- df %>%
    mutate(
      Var2   = factor(Var2, levels = sort(unique(Var2), decreasing = TRUE)),
      signal = factor(signal, levels = c("strong", "weak")),
      L1     = factor(L1, levels = method_levels),
      mark   = case_when(
        crit_fulfilled == "green" ~ "\u2714",
        crit_fulfilled == "red"   ~ "\u2716",
        TRUE ~ ""
      ),
      modelsize_label = paste0("(", round(modelsize, 1), ")")
    )
  
  df_bg <- tibble(
    L1      = factor(method_levels, levels = method_levels),
    xmin    = -Inf,
    xmax    = +Inf,
    ymin    = -Inf,
    ymax    = +Inf,
    bg_fill = facet_bg_colors[method_levels]
  )
  
  method_labels_2line <- setNames(
    paste0(method_labels[method_levels], "\nstrong  |  weak"),
    method_levels
  )
  
  ggplot() +
    geom_rect(data = df_bg,
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
              fill = df_bg$bg_fill, color = NA, inherit.aes = FALSE, alpha = 1) +
    geom_tile(data = df_plot,
              aes(x = signal, y = Var2, fill = crit_fulfilled),
              color = "white", width = 0.82, height = 0.92) +
    geom_text(data = df_plot %>% filter(crit_fulfilled == "green"),
              aes(x = signal, y = Var2, label = mark),
              color = "#1a7a1a", size = 3.5, hjust = 0, nudge_x = -0.3,
              vjust = 0.5, nudge_y = 0) +
    geom_text(data = df_plot %>% filter(crit_fulfilled == "red"),
              aes(x = signal, y = Var2, label = mark),
              size = 3.5,
              hjust = 0, nudge_x = -0.3, vjust = 0.5, nudge_y = 0) +
    geom_text(data = df_plot,
              aes(x = signal, y = Var2, label = modelsize_label),
              color = "black", size = 3.0, hjust = 0,
              nudge_x = -0.05, vjust = 0.5, nudge_y = 0) +
    scale_fill_manual(values = c("green" = "#b8eab8", "red" = "#f5b8b8")) +
    facet_wrap(~ L1, ncol = length(method_levels),
               labeller = as_labeller(method_labels_2line)) +
    labs(x = NULL, y = "Sample size", fill = NULL, title = title) +
    scale_y_discrete(expand = expansion(add = 0.5),
                     sec.axis = dup_axis(name = "EPV", labels = rev(epv_labels))) +
    theme_minimal(base_size = 12) +
    theme(
      panel.grid             = element_blank(),
      strip.text             = element_text(face = "bold", size = 11, lineheight = 1.1),
      axis.text.x            = element_blank(),
      axis.text.x.top        = element_blank(),
      axis.ticks.x           = element_blank(),
      axis.ticks.x.top       = element_blank(),
      axis.ticks.length.x    = unit(0, "pt"),
      axis.ticks.length.x.top = unit(0, "pt"),
      axis.title.x           = element_blank(),
      axis.title.x.top       = element_blank(),
      axis.text.y            = element_text(size = 10),
      axis.title.y           = element_text(size = 11),
      aspect.ratio         = NULL,
      plot.title             = element_text(face = "bold", size = 14, margin = margin(t = 6, b = 2)),
      plot.title.position    = "plot",
      panel.spacing.x        = unit(2, "pt"),
      plot.margin            = margin(2, 3, 16, 3),
      legend.position        = "none"
    )
}

# Helper: color facet strip backgrounds per-method using gtable manipulation.
# methods_ord: names of methods in facet order. Defaults to the full 8-method order;
#   pass a subset vector when colouring narrow group plots.
color_strips <- function(p, facet_bg_colors, methods_ord = NULL) {
  if (is.null(methods_ord)) {
    methods_ord <- c("Lasso", "BE_05", "BE_AIC", "AdaLasso", "RLasso",
                     "BE_005", "BE_BIC", "RLasso_BIC")
  }
  g <- ggplotGrob(p)
  strip_names <- g$layout$name[grepl("^strip-t", g$layout$name)]
  for (i in seq_along(strip_names)) {
    col <- facet_bg_colors[methods_ord[i]]
    strip_idx <- which(g$layout$name == strip_names[i])
    g$grobs[[strip_idx]]$grobs[[1]]$children[[1]] <-
      grid::rectGrob(gp = grid::gpar(fill = col, col = NA))
  }
  g
}

create_tile_plot <- function(TPR_mild_group, FPR_mild_group,
                             TPR_medium_group, FPR_medium_group,
                             TPR_strict_group, FPR_strict_group,
                             ann_text_size = 4.2,
                             ann_rel_height = 3.2,
                             corr_setting = "nhanes") {
  
  # Select precomp objects based on correlation setting
  if (corr_setting == "nhanes") {
    pc_log03  <- precomp_nhanes_log03
    pc_log005 <- precomp_nhanes_log005
    pc_lin    <- precomp_nhanes_lin
  } else {
    pc_log03  <- precomp_nocorr_log03
    pc_log005 <- precomp_nocorr_log005
    pc_lin    <- precomp_nocorr_lin
  }
  
  plot_log03 <- create_tiles(pc_log03,
                             TPR_mild_group, FPR_mild_group,
                             TPR_medium_group, FPR_medium_group,
                             TPR_strict_group, FPR_strict_group)
  
  plot_log005 <- create_tiles(pc_log005,
                              TPR_mild_group, FPR_mild_group,
                              TPR_medium_group, FPR_medium_group,
                              TPR_strict_group, FPR_strict_group)
  
  plot_lin <- create_tiles(pc_lin,
                           TPR_mild_group, FPR_mild_group,
                           TPR_medium_group, FPR_medium_group,
                           TPR_strict_group, FPR_strict_group)
  
  tile_bg_colors <- c(
    "Lasso" = "#e6f2ff", "BE_05" = "#e6f2ff",
    "BE_AIC" = "#fff5e6", "AdaLasso" = "#fff5e6", "RLasso" = "#fff5e6",
    "BE_005" = "#f2e6ff", "BE_BIC" = "#f2e6ff", "RLasso_BIC" = "#f2e6ff"
  )
  g_log03  <- color_strips(plot_log03,  tile_bg_colors)
  g_log005 <- color_strips(plot_log005, tile_bg_colors)
  g_lin    <- color_strips(plot_lin,    tile_bg_colors)
  
  # per-group threshold labels
  # Build an annotation row that reuses the same facet_wrap(~ L1, ncol=8)
  # structure as the tile plots, so columns are guaranteed to align.
  # Each facet shows a single coloured label; the middle facet of each group
  # carries the threshold text, the others are blank.
  method_levels_ann <- c("Lasso", "BE_05", "BE_AIC", "AdaLasso", "RLasso",
                         "BE_005", "BE_BIC", "RLasso_BIC")
  
  group1_label <- paste0("MILD SELECTION\nTPR\u2265", TPR_mild_group,
                         "\nFPR\u2264", FPR_mild_group)
  group2_label <- paste0("BALANCED SELECTION\nTPR\u2265", TPR_medium_group,
                         "\nFPR\u2264", FPR_medium_group)
  group3_label <- paste0("STRICT SELECTION\nTPR\u2265", TPR_strict_group,
                         "\nFPR\u2264", FPR_strict_group)
  
  # Label placement: one label per group, in the middle (or left-of-middle) facet.
  # Group 1: 2 facets (Lasso, BE_05) - label in Lasso only, slightly right-of-center
  #          using x = 2.0 so it visually centers across both columns.
  # Group 2: 3 facets (BE_AIC, AdaLasso, RLasso) - label in middle (AdaLasso).
  # Group 3: 3 facets (BE_005, BE_BIC, RLasso_BIC) - label in middle (BE_BIC).
  ann_text <- c(
    Lasso      = group1_label,
    BE_05      = "",
    BE_AIC     = "",
    AdaLasso   = group2_label,
    RLasso     = "",
    BE_005     = "",
    BE_BIC     = group3_label,
    RLasso_BIC = ""
  )
  ann_x <- c(
    Lasso = 2.0,   # right-of-center in Lasso facet to visually span into BE_05
    BE_05 = 1.5, BE_AIC = 1.5, AdaLasso = 1.5, RLasso = 1.5,
    BE_005 = 1.5, BE_BIC = 1.5, RLasso_BIC = 1.5
  )
  ann_bg <- c(
    Lasso = "#e6f2ff", BE_05 = "#e6f2ff",
    BE_AIC = "#fff5e6", AdaLasso = "#fff5e6", RLasso = "#fff5e6",
    BE_005 = "#f2e6ff", BE_BIC = "#f2e6ff", RLasso_BIC = "#f2e6ff"
  )
  
  # Annotation row: single continuous-axis ggplot, no facets
  # Columns 1-8 map to: Lasso, BE_05, BE_AIC, AdaLasso, RLasso, BE_005, BE_BIC, RLasso_BIC
  # Group spans: mild=1-2, intermediate=3-5, strict=6-8
  # Background rects and text are all in one coordinate system - no facet clipping.
  ann_rects <- data.frame(
    xmin = c(0.5, 2.5, 5.5),
    xmax = c(2.5, 5.5, 8.5),
    bg   = c("#e6f2ff", "#fff5e6", "#f2e6ff")
  )
  ann_labels <- data.frame(
    x     = c(1.5, 4.0, 7.0),   # center of each group span
    label = c(group1_label, group2_label, group3_label)
  )
  
  ann_plot <- ggplot() +
    geom_rect(data = ann_rects,
              aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = bg),
              color = NA, inherit.aes = FALSE) +
    scale_fill_identity() +
    geom_text(data = ann_labels,
              aes(x = x, y = 0.5, label = label),
              hjust = 0.5, vjust = 0.5, size = ann_text_size,
              lineheight = 1.2, fontface = "bold", color = "black") +
    scale_x_continuous(limits = c(0.5, 8.5), expand = c(0, 0)) +
    scale_y_continuous(limits = c(0, 1), expand = c(0, 0),
                       sec.axis = dup_axis(name = "EPV", labels = NULL,
                                           breaks = NULL)) +
    labs(x = NULL, y = "Sample size", fill = NULL) +
    theme_minimal(base_size = 12) +
    theme(
      panel.grid         = element_blank(),
      axis.text          = element_blank(),
      axis.ticks         = element_blank(),
      axis.ticks.length  = unit(0, "pt"),
      axis.title.y       = element_text(size = 11, color = "transparent"),
      plot.margin        = margin(3, 3, 3, 3),
      legend.position    = "none"
    )
  
  # cowplot handles gtables natively - no wrap_elements needed.
  # Use rel_heights proportional to row counts so plots scale with available space.
  # log03=8 rows, log005=4 rows, lin=8 rows, annotation=small fixed fraction.
  cowplot::plot_grid(
    g_lin, g_log03, g_log005, ann_plot,
    ncol = 1,
    rel_heights = c(8 + 2.0, 8 + 2.0, 4 + 3.5, ann_rel_height),
    align = "v",
    axis  = "lr"
  )
}

#  Build a narrow single-scenario - single-group plot (win_width < 900)
# One precomp (scenario) - one group: used in the 9-panel narrow layout where
# plots are ordered by regression type first, then mild / balanced / strict.
# precomp: one of precomp_log03, precomp_log005, precomp_lin
# group:   one of "mild", "balanced", "strict"
create_tile_single <- function(precomp, group,
                               TPR_mild_group, FPR_mild_group,
                               TPR_medium_group, FPR_medium_group,
                               TPR_strict_group, FPR_strict_group,
                               ann_text_size = 4.2,
                               ann_rel_height = 3.2,
                               corr_setting = "nhanes") {
  
  methods_map <- list(
    mild     = c("Lasso", "BE_05"),
    balanced = c("BE_AIC", "AdaLasso", "RLasso"),
    strict   = c("BE_005", "BE_BIC", "RLasso_BIC")
  )
  group_colors <- c(mild = "#e6f2ff", balanced = "#fff5e6", strict = "#f2e6ff")
  group_labels <- list(
    mild     = paste0("MILD SELECTION\nTPR\u2265", TPR_mild_group,
                      "\nFPR\u2264", FPR_mild_group),
    balanced = paste0("BALANCED SELECTION\nTPR\u2265", TPR_medium_group,
                      "\nFPR\u2264", FPR_medium_group),
    strict   = paste0("STRICT SELECTION\nTPR\u2265", TPR_strict_group,
                      "\nFPR\u2264", FPR_strict_group)
  )
  
  msub <- methods_map[[group]]
  gcol <- group_colors[group]
  glbl <- group_labels[[group]]
  nm   <- length(msub)
  
  tile_bg_colors <- c(
    "Lasso" = "#e6f2ff", "BE_05" = "#e6f2ff",
    "BE_AIC" = "#fff5e6", "AdaLasso" = "#fff5e6", "RLasso" = "#fff5e6",
    "BE_005" = "#f2e6ff", "BE_BIC" = "#f2e6ff", "RLasso_BIC" = "#f2e6ff"
  )
  
  # Build tile plot for this one scenario, subset to this group's methods
  p <- create_tiles(precomp,
                    TPR_mild_group, FPR_mild_group,
                    TPR_medium_group, FPR_medium_group,
                    TPR_strict_group, FPR_strict_group,
                    methods_subset = msub)
  g <- color_strips(p, tile_bg_colors, msub)
  
  # Annotation row spanning this group's methods
  ann_rects  <- data.frame(xmin = 0.5, xmax = nm + 0.5, bg = gcol)
  ann_labels <- data.frame(x = (nm + 1) / 2, label = glbl)
  
  ann_plot <- ggplot() +
    geom_rect(data = ann_rects,
              aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, fill = bg),
              color = NA, inherit.aes = FALSE) +
    scale_fill_identity() +
    geom_text(data = ann_labels,
              aes(x = x, y = 0.5, label = label),
              hjust = 0.5, vjust = 0.5, size = ann_text_size,
              lineheight = 1.2, fontface = "bold", color = "black") +
    scale_x_continuous(limits = c(0.5, nm + 0.5), expand = c(0, 0)) +
    scale_y_continuous(limits = c(0, 1), expand = c(0, 0),
                       sec.axis = dup_axis(name = "EPV", labels = NULL,
                                           breaks = NULL)) +
    labs(x = NULL, y = "Sample size", fill = NULL) +
    theme_minimal(base_size = 12) +
    theme(
      panel.grid         = element_blank(),
      axis.text          = element_blank(),
      axis.ticks         = element_blank(),
      axis.ticks.length  = unit(0, "pt"),
      axis.title.y       = element_text(size = 11, color = "transparent"),
      plot.margin        = margin(3, 3, 3, 3),
      legend.position    = "none"
    )
  
  # rel_heights: tile area (8 units) + annotation.
  # Actual pixel height is controlled by CSS (proportional to scenario row count).
  cowplot::plot_grid(
    g, ann_plot,
    ncol        = 1,
    rel_heights = c(8, ann_rel_height),
    align       = "v",
    axis        = "lr"
  )
}

ui <- navbarPage(
  title = "Choosing A Variable Selection Method via the TPR-FPR Trade-off",
  header = tags$head(
    tags$style(HTML("
      .irs--shiny .irs-bar, .irs--shiny .irs-line { height: 4px; }
      .irs--shiny .irs-handle { width: 16px; height: 16px; top: 22px; }
      .form-group { margin-bottom: 8px; }
      label { font-size: 12px; margin-bottom: 1px; }
      /* Keep sidebar group headers on one line */
      .well h4 { font-size: 13px; line-height: 1.3; white-space: nowrap; }
      /* Wide plot + all narrow single-scenario/group plots */
      #tilePlot, [id^='tilePlot_'] { width: 100%; }
      .intro-box {
        background-color: #f8f9fa;
        border-left: 4px solid #4a90d9;
        border-radius: 4px;
        padding: 12px 16px;
        margin-bottom: 14px;
        font-size: 14px;
        color: #333;
      }
      .intro-box h4 {
        margin-top: 0;
        margin-bottom: 6px;
        font-size: 15px;
        color: #2c3e50;
      }
      .howto-box {
        background-color: #fff;
        border: 1px solid #dde;
        border-radius: 4px;
        padding: 10px 16px;
        margin-bottom: 14px;
        font-size: 14px;
        color: #333;
      }
      .howto-box h4 {
        margin-top: 0;
        margin-bottom: 6px;
        font-size: 15px;
        color: #2c3e50;
      }
      .howto-box ol {
        margin: 0;
        padding-left: 20px;
      }
      .howto-box ol li {
        margin-bottom: 3px;
      }
      .simdesign-content {
        max-width: 900px;
        margin: 0 auto;
        padding: 10px 20px 30px 20px;
        font-size: 14px;
        line-height: 1.6;
      }
      .simdesign-content h1 {
        font-size: 1.8em;
        margin-top: 16px;
        margin-bottom: 16px;
        border-bottom: 2px solid #ccc;
        padding-bottom: 6px;
      }
      .simdesign-content h2 {
        font-size: 1.3em;
        margin-top: 24px;
        border-bottom: 1px solid #ddd;
        padding-bottom: 4px;
      }
      .simdesign-content h3 {
        font-size: 1.05em;
        margin-top: 18px;
        color: #2c3e50;
      }
      .simdesign-content img {
        max-width: 100%;
        display: block;
        margin: 12px auto;
      }
    ")),
    tags$script(HTML("
      function applyLayout() {
        var W    = window.innerWidth;
        var navH = $('.navbar').outerHeight(true) || 50;
        var h    = Math.max(500, window.innerHeight - navH - 20);

        // Wide plot height
        $('#tilePlot').css('height', h + 'px');

        // Narrow plots: 9 panels ordered by scenario then group.
        // Heights proportional to scenario row counts:
        //   linear and log03: 8 EPV rows  ??? ~38% of win_height
        //   log0.05:          4 EPV rows  ??? ~28% of win_height
        var hlin = Math.max(250, Math.round(h * 0.38));
        var h03  = Math.max(250, Math.round(h * 0.38));
        var h005 = Math.max(200, Math.round(h * 0.28));
        $('#tilePlot_lin_mild, #tilePlot_lin_balanced, #tilePlot_lin_strict').css('height', hlin + 'px');
        $('#tilePlot_log03_mild, #tilePlot_log03_balanced, #tilePlot_log03_strict').css('height', h03  + 'px');
        $('#tilePlot_log005_mild, #tilePlot_log005_balanced, #tilePlot_log005_strict').css('height', h005 + 'px');

        // Sidebar: ~220px on small screens, ~260px on large screens
        var sbW = W < 1200 ? 220 : 260;
        $('.col-sm-2').css('width', sbW + 'px').css('flex', 'none');
        $('.col-sm-10').css('width', 'calc(100% - ' + sbW + 'px)').css('flex', 'none');

        // Inform Shiny of window dimensions for server-side scaling
        Shiny.setInputValue('win_width',  W);
        Shiny.setInputValue('win_height', h);
      }
      $(document).ready(applyLayout);
      $(window).resize(applyLayout);
    "))
  ),
  
  # Tab 1: Interactive threshold explorer
  tabPanel(
    "Threshold Explorer",
    sidebarLayout(
      sidebarPanel(
        width = 2,
        
        # MILD SELECTION
        tags$h4(tags$span(style = "background-color:#e6f2ff; padding:2px 6px; border-radius:4px;",
                          "MILD SELECTION")),
        tags$p(tags$em(style = "font-size:12px; color:#555;",
                       "Methods: BE(0.50), Lasso(CV)")),
        sliderInput("TPR_mild", "Min. TPR",
                    min = 0, max = 1, value = 0.95, step = 0.05),
        sliderInput("FPR_mild", "Max. FPR",
                    min = 0, max = 1, value = 0.75, step = 0.05),
        
        tags$hr(),
        
        # BALANCED SELECTION
        tags$h4(tags$span(style = "background-color:#fff5e6; padding:2px 6px; border-radius:4px;",
                          "BALANCED SELECTION")),
        tags$p(tags$em(style = "font-size:12px; color:#555;",
                       "Methods: BE(AIC), RLasso(CV), AdaLasso(CV)")),
        sliderInput("TPR_medium", "Min. TPR",
                    min = 0, max = 1, value = 0.80, step = 0.05),
        sliderInput("FPR_medium", "Max. FPR",
                    min = 0, max = 1, value = 0.20, step = 0.05),
        
        tags$hr(),
        
        # STRICT SELECTION
        tags$h4(tags$span(style = "background-color:#f2e6ff; padding:2px 6px; border-radius:4px;",
                          "STRICT SELECTION")),
        tags$p(tags$em(style = "font-size:12px; color:#555;",
                       "Methods: BE(BIC), BE(0.05), RLasso(BIC)")),
        sliderInput("TPR_strict", "Min. TPR",
                    min = 0, max = 1, value = 0.50, step = 0.05),
        sliderInput("FPR_strict", "Max. FPR",
                    min = 0, max = 1, value = 0.10, step = 0.05),
        
        tags$hr(),
        
        # CORRELATION STRUCTURE SELECTOR
        tags$p(tags$strong("Correlation structure"),
               style = "margin-bottom:4px; font-size:12px;"),
        tags$div(
          style = "display:flex; width:100%; margin-bottom:10px;",
          tags$button(
            id = "btn_nhanes", type = "button",
            style = paste0(
              "flex:1; padding:4px 2px; font-size:11px; cursor:pointer;",
              "border:1px solid #4a90d9; border-radius:4px 0 0 4px;",
              "background-color:#4a90d9; color:white; font-weight:bold;"
            ),
            onclick = "Shiny.setInputValue('corr_setting', 'nhanes', {priority: 'event'});
                       this.style.backgroundColor='#4a90d9'; this.style.color='white'; this.style.fontWeight='bold';
                       document.getElementById('btn_none').style.backgroundColor='white';
                       document.getElementById('btn_none').style.color='#333';
                       document.getElementById('btn_none').style.fontWeight='normal';",
            "Realistic (NHANES)"
          ),
          tags$button(
            id = "btn_none", type = "button",
            style = paste0(
              "flex:1; padding:4px 2px; font-size:11px; cursor:pointer;",
              "border:1px solid #4a90d9; border-left:none; border-radius:0 4px 4px 0;",
              "background-color:white; color:#333; font-weight:normal;"
            ),
            onclick = "Shiny.setInputValue('corr_setting', 'none', {priority: 'event'});
                       this.style.backgroundColor='#4a90d9'; this.style.color='white'; this.style.fontWeight='bold';
                       document.getElementById('btn_nhanes').style.backgroundColor='white';
                       document.getElementById('btn_nhanes').style.color='#333';
                       document.getElementById('btn_nhanes').style.fontWeight='normal';",
            "No correlations"
          )
        ),
        
        actionButton("update", "Update plot",
                     class = "btn-primary", style = "width:100%;")
      ),
      
      mainPanel(
        width = 10,
        
        # Introduction
        tags$div(class = "intro-box",
                 tags$h3("About this app"),
                 tags$p(
                   "This app presents results from a simulation study comparing variable selection methods
            for multivariable linear and logistic regression in a descriptive modelling context.
            Variable selection methods differ substantially in their true and false positive rates (TPR/FPR)
            of the selected models, and the best choice of method depends on the TPR\u2013FPR trade-off
            that is acceptable for a given study: ",
                   tags$strong("mild methods prioritize retaining relevant variables (high TPR),
            strict methods prioritize excluding noise variables (low FPR),
            and balanced methods offer a compromise."),
                   " Methods are grouped as follows:"
                 ),
                 tags$ul(
                   tags$li(
                     tags$strong("Mild selection: BE(0.50) and Lasso(CV)"),
                     " \u2014 liberal criteria, tend to retain more variables."
                   ),
                   tags$li(
                     tags$strong("Balanced selection: BE(AIC), RLasso(CV), and AdaLasso(CV)"),
                     " \u2014 strike a balance between sensitivity and specificity."
                   ),
                   tags$li(
                     tags$strong("Strict selection: BE(BIC), BE(0.05), and RLasso(BIC)"),
                     " \u2014 conservative criteria, select fewer variables."
                   )
                 ),
                 tags$p(
                   "The simulation comprised ",
                   tags$b("20 independent variables (10 true predictors and 10 noise variables)"),
                   " whose marginal distributions were derived from data of the National Health and Nutrition Examination Survey (NHANES). Two settings for the correlation structure are available: a realistic correlation structure derived from NHANES, and a setting with no correlations between variables (both sharing the same marginal distributions). Predictor effects were chosen to represent a realistic mixture of stronger and weaker associations. ",
                   "Three regression types were evaluated: ",
                   tags$b("linear regression, and logistic regression with event rates of 0.3 and 0.05,"),
                   " across a range of sample sizes. ",
                   "Two signal strength settings were considered:"
                 ),
                 tags$table(
                   class = "table table-sm",
                   tags$thead(
                     tags$tr(
                       tags$th("Regression"),
                       tags$th("Strong signal"),
                       tags$th("Weak signal")
                     )
                   ),
                   tags$tbody(
                     tags$tr(
                       tags$td("Linear"),
                       tags$td(HTML("R&sup2; = 0.45")),
                       tags$td(HTML("R&sup2; = 0.15"))
                     ),
                     tags$tr(
                       tags$td("Logistic with event rate 0.3"),
                       tags$td(HTML("Cox-Snell R&sup2; = 0.40")),
                       tags$td(HTML("Cox-Snell R&sup2; = 0.13"))
                     ),
                     tags$tr(
                       tags$td("Logistic with event rate 0.05"),
                       tags$td(HTML("Cox-Snell R&sup2; = 0.16")),
                       tags$td(HTML("Cox-Snell R&sup2; = 0.05"))
                     )
                   )
                 ),
                 tags$p(
                   "For full details on the simulation design, see the ",
                   tags$strong("Simulation Design"),
                   " tab."
                 )
        ),
        
        # How to use
        tags$div(class = "howto-box",
                 tags$h3("How to use"),
                 tags$ol(
                   tags$li(HTML(
                     "<strong>Consider your research context:</strong> Think about whether missing a true
                     association or reporting a spurious one is more harmful, and identify the method group
                     that best matches your aim &mdash; mild, balanced, or strict. For example, if a poorly
                     understood condition is studied where little prior knowledge exists and missing a true
                     association could mean it goes entirely unnoticed, mild selection (prioritizing high TPR)
                     may be preferable. If the goal is to identify a reliable set of associated variables to
                     inform the design of a resource-intensive follow-up study, where including spurious
                     associations would waste resources or misdirect future research, strict selection
                     (prioritizing low FPR) may be more appropriate. For most routine descriptive analyses,
                     a balance between the two is desirable, for which the balanced-selection methods are a
                     natural starting point."
                   )),
                   tags$li(HTML(
                     "<strong>Set the thresholds:</strong> Use the sliders to choose the specific TPR and
                     FPR thresholds that are acceptable for your chosen group."
                   )),
                   tags$li(HTML(
                     "<strong>Update the plot:</strong> Click <strong>Update plot</strong> to apply the
                     thresholds and refresh the tile plot."
                   )),
                   tags$li(HTML(
                     "<strong>Read the tiles:</strong> Each tile represents one combination of method,
                     signal strength (strong&nbsp;|&nbsp;weak), and sample size (left axis) or EPV (right
                     axis). A green tile (\u2714) means the criterion is met; a red tile (\u2716) means it
                     is not. Numbers in parentheses show the mean number of selected variables. If all tiles
                     are red for your scenario, the EPV and/or signal strength are too low for reliable
                     data-driven selection, and the full model (FU) should be used instead."
                   ))
                 )
        ),
        
        fluidRow(
          column(12,
                 tags$div(style = "display:flex; gap:24px; align-items:center; margin-bottom:8px; font-size:14px;",
                          tags$span(
                            HTML('<span style="background:#b8eab8; padding:2px 8px; border-radius:3px; margin-right:4px; color:#1a7a1a; font-size:16px;">&#x2714;</span>'),
                            " Criterion met (green)"),
                          tags$span(
                            HTML('<span style="background:#f5b8b8; padding:2px 8px; border-radius:3px; margin-right:4px; color:#666666; font-size:16px;">&#x2716;</span>'),
                            " Criterion not met (red)"),
                          tags$span(tags$em("Numbers in parentheses = mean model size"))
                 )
          )
        ),
        # Wide plot: only shown once JS has confirmed win_width >= 900
        conditionalPanel(
          condition = "input.win_width && input.win_width >= 900",
          plotOutput("tilePlot", height = "auto", width = "100%")
        ),
        # Narrow plots: default until JS fires (win_width not yet set), then win_width < 900
        # 9 panels ordered by regression scenario first, then selection group.
        conditionalPanel(
          condition = "!input.win_width || input.win_width < 900",
          # Linear regression
          plotOutput("tilePlot_lin_mild",     height = "auto", width = "100%"),
          plotOutput("tilePlot_lin_balanced", height = "auto", width = "100%"),
          plotOutput("tilePlot_lin_strict",   height = "auto", width = "100%"),
          # Logistic regression, event rate 0.3
          plotOutput("tilePlot_log03_mild",     height = "auto", width = "100%"),
          plotOutput("tilePlot_log03_balanced", height = "auto", width = "100%"),
          plotOutput("tilePlot_log03_strict",   height = "auto", width = "100%"),
          # Logistic regression, event rate 0.05
          plotOutput("tilePlot_log005_mild",     height = "auto", width = "100%"),
          plotOutput("tilePlot_log005_balanced", height = "auto", width = "100%"),
          plotOutput("tilePlot_log005_strict",   height = "auto", width = "100%")
        )
      )
    )
  ),
  
  # Tab 2: Simulation design
  tabPanel(
    "Simulation Design",
    tags$div(class = "simdesign-content",
             tags$h1("Simulation design"),
             tags$p(HTML(
               'Here we briefly describe our simulation design. More details can be found in the manuscript and the <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0308543">study protocol</a>.'
             )),
             tags$h2("Aim"),
             tags$p("We aimed to compare different variable selection methods for multivariable linear or logistic
             regression in the context of descriptive modeling."),
             
             tags$h2("Data generating mechanisms"),
             
             tags$h3("Simulation of independent variables"),
             tags$ul(
               tags$li(HTML("20 independent variables X<sub>1</sub>,\u2026,X<sub>20</sub>
                     (10 true predictors and 10 noise variables)")),
               tags$li("Correlation structure and distributions of the variables were based on data from the
                National Health and Nutrition Examination Survey (NHANES)")
             ),
             tags$img(src = "figure/correlation_heatmap.png",
                      alt = "Correlation heatmap of predictor variables",
                      style = "max-width:600px;"),
             
             tags$h3("Simulation of outcome Y"),
             tags$ul(
               tags$li("Standardized beta coefficients of predictors were chosen to obtain a mixture of stronger
                and weaker effects."),
               tags$li(HTML("For <strong>linear regression</strong>: outcomes were calculated as
                     Y = x&beta; + &epsilon;, with &epsilon; ~ N(0, &sigma;<sup>2</sup>), and
                     &sigma;<sup>2</sup> chosen such that R<sup>2</sup> = 0.45 (strong signal) or
                     R<sup>2</sup> = 0.15 (weak signal).")),
               tags$li(HTML("For <strong>logistic regression</strong>: outcomes Y were drawn from a Bernoulli
                     distribution with event probability 1 / (1 + exp(&minus;c x&beta;)), with a constant
                     c &gt; 0. We adjusted c and the intercept &beta;<sub>0</sub> to obtain different
                     event rates (0.3 and 0.05) and Cox&ndash;Snell R<sup>2</sup><sub>CS</sub> values
                     (strong or weak signal)."))
             ),
             
             tags$h3("Simulation settings"),
             tags$table(
               style = "border-collapse: collapse; font-size: 13px; margin: 10px auto;",
               
               tags$head(
                 tags$style(HTML("
.simtbl { border-collapse: collapse; font-size: 13px; margin: 10px auto; }
.simtbl th, .simtbl td { border: 1px solid #bbb; padding: 6px 12px; }
.simtbl th { background-color: #f0f0f0; text-align: center; }
.simtbl td:first-child { text-align: left; }
.simtbl td:not(:first-child) { text-align: center; }
"))
               ),
               tags$table(
                 class = "simtbl",
                 tags$thead(
                   tags$tr(
                     tags$th(""),
                     tags$th("Linear regression"),
                     tags$th(HTML("Logistic regression event rate 0.3")),
                     tags$th(HTML("Logistic regression event rate 0.05"))
                   )
                 ),
                 tags$tbody(
                   tags$tr(
                     tags$td("Strong signal strength"),
                     tags$td(HTML("<em>R</em><sup>2</sup> = 0.45")),
                     tags$td(HTML("<em>R</em><sup>2</sup><sub>CS</sub> = 0.40")),
                     tags$td(HTML("<em>R</em><sup>2</sup><sub>CS</sub> = 0.16"))
                   ),
                   tags$tr(
                     tags$td("Weak signal strength"),
                     tags$td(HTML("<em>R</em><sup>2</sup> = 0.15")),
                     tags$td(HTML("<em>R</em><sup>2</sup><sub>CS</sub> = 0.13")),
                     tags$td(HTML("<em>R</em><sup>2</sup><sub>CS</sub> = 0.05"))
                   )
                 )
               )
             ),
             
             tags$h3("Sample sizes and events-per-variable (EPV) values"),
             tags$head(
               tags$style(HTML("
.simgrid { border-collapse: collapse; font-size: 13px; margin: 10px auto; }
.simgrid td { border: 1px solid #bbb; padding: 6px 10px; }
.simgrid td:first-child { text-align: left; }
.simgrid td:not(:first-child) { text-align: center; }
.simgrid .rowhdr { vertical-align: middle; font-weight: 500; }
.simgrid .italic { font-style: italic; }
"))
             ),
             
             
             tags$table(
               class = "simgrid",
               tags$tbody(
                 # linear regression
                 tags$tr(
                   tags$td(rowspan = 2, class = "rowhdr", "linear regression"),
                   tags$td(class = "italic", "n"),
                   tags$td("100"),
                   tags$td("200"),
                   tags$td("400"),
                   tags$td(class = "italic", "500"),
                   tags$td("800"),
                   tags$td("1600"),
                   tags$td("3200"),
                   tags$td("6400")
                 ),
                 tags$tr(
                   tags$td("EPV"),
                   tags$td("5"),
                   tags$td("10"),
                   tags$td("20"),
                   tags$td(class = "italic", "25"),
                   tags$td("40"),
                   tags$td("80"),
                   tags$td("160"),
                   tags$td("320")
                 ),
                 
                 
                 # logistic regression, event rate 0.3
                 tags$tr(
                   tags$td(rowspan = 2, class = "rowhdr", HTML("logistic regression,<br>event rate 0.3")),
                   tags$td(class = "italic", "n"),
                   tags$td("183"),
                   tags$td("365"),
                   tags$td("730"),
                   tags$td(class = "italic", "1667"),
                   tags$td("1461"),
                   tags$td("2922"),
                   tags$td("5844"),
                   tags$td("11,687")
                 ),
                 tags$tr(
                   tags$td("EPV"),
                   tags$td("2.75"),
                   tags$td("5.48"),
                   tags$td("10.95"),
                   tags$td(class = "italic", "25"),
                   tags$td("21.92"),
                   tags$td("43.83"),
                   tags$td("87.66"),
                   tags$td("175.31")
                 ),
                 
                 # logistic regression, event rate 0.05
                 tags$tr(
                   tags$td(rowspan = 2, class = "rowhdr", HTML("logistic regression,<br>event rate 0.05")),
                   tags$td(class = "italic", "n"),
                   tags$td("2000"),
                   tags$td("4000"),
                   tags$td("8000"),
                   tags$td(class = "italic", "10,000"),
                   tags$td("\u2014"),
                   tags$td("\u2014"),
                   tags$td("\u2014"),
                   tags$td("\u2014")
                 ),
                 tags$tr(
                   tags$td("EPV"),
                   tags$td("5"),
                   tags$td("10"),
                   tags$td("20"),
                   tags$td(class = "italic", "25"),
                   tags$td("\u2014"),
                   tags$td("\u2014"),
                   tags$td("\u2014"),
                   tags$td("\u2014")
                 )
                 
               )
             ),
             
             
             tags$h2("Estimands and targets relevant for this app"),
             tags$ul(
               tags$li("Model selection (e.g., whether the true model is selected)")
             ),
             
             tags$h2("Methods"),
             tags$ul(
               tags$li(HTML("<strong>BE(BIC), BE(0.05), BE(AIC), BE(0.5)</strong>: Backward elimination with BIC,
                     with &alpha; = 0.05, with AIC, or with &alpha; = 0.5")),
               tags$li(HTML("<strong>Lasso(CV)</strong>: Lasso with complexity parameter &lambda; tuned with
                     10-fold cross-validation")),
               tags$li(HTML("<strong>RLasso(CV), RLasso(BIC)</strong>: Relaxed Lasso with complexity parameter &lambda; tuned
                     with 10-fold cross-validation or with BIC")),
               tags$li(HTML("<strong>AdaLasso(CV)</strong>: Adaptive Lasso with complexity parameter &lambda; tuned
                     with 10-fold cross-validation"))
             ),
             
             tags$h2("Performance measures relevant for this app"),
             tags$ul(
               tags$li("True positive rate: selection rates of true predictors"),
               tags$li("False positive rate: selection rates of noise variables")
             ),
             tags$h3("Additional measure"),
             tags$ul(
               tags$li("Model size: number of selected variables")
             ),
             tags$p("Results were averaged over 2000 simulation repetitions.")
    )
  ),
  
  # Tab 3: About
  tabPanel(
    "About",
    fluidRow(
      column(8, offset = 2,
             tags$br(),
             tags$h3("About"),
             tags$p("Results of a simulation study that compared different methods for variable selection."),
             
             tags$h3("Authors"),
             tags$p("Theresa Ullmann, Georg Heinze, Michael Kammer, Daniela Dunkler"),
             
             tags$h3("Contact"),
             tags$p(
               "Theresa Ullmann", tags$br(),
               tags$br(),
               "Medical University of Vienna", tags$br(),
               "Center for Medical Data Science", tags$br(),
               tags$a("Institute of Clinical Biometrics",
                      href = "https://data-science.meduniwien.ac.at/en/institutes/clinical-biometrics/"), tags$br(),
               "Spitalgasse 23, BT88", tags$br(),
               "1090 Vienna", tags$br(),
               "Austria", tags$br(),
               tags$br(),
               tags$p("theresa.ullmann [at] meduniwien.ac.at")
             ),
             
             tags$h3("Code"),
             tags$p(HTML(
               'This app is implemented in the R Shiny web application framework and is deployed through
               RStudio\'s webservice <a href="https://www.shinyapps.io/">shinyapps.io</a>.
               The code is available in the accompanying
               <a href="https://github.com/biometrician/VariableSelection/">Github</a> repository.'
             )),
             
             tags$h3("Reference"),
             
             tags$p(
               "Ullmann, T., Heinze, G., Kammer, M., Dunkler, D. for TG2 of the STRATOS initiative (2026). ",
               "A preregistered simulation study provided evidence on the appropriate use of data-driven variable selection in descriptive multivariable regression modeling. ",
               tags$em("Currently under review")
             ),
             
             tags$p(HTML(
               'Ullmann, T., Heinze, G., Hafermann, L., Schilhart-Wallisch, C., Dunkler, D. for TG2 of the STRATOS initiative (2024).
               Evaluating variable selection methods for multivariable regression models: A simulation study protocol.
               <em>PLOS ONE</em>, 19(8),
               <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0308543">e0308543</a>.'
             ))
      )
    )
  )
)

#####################################################################################
# SHINY SERVER
#####################################################################################

server <- function(input, output, session) {
  
  
  # Shared helper: annotation scaling based on window height
  get_ann_params <- function() {
    h <- if (!is.null(input$win_height) && input$win_height > 0)
      input$win_height else 900
    list(
      ann_size       = max(2.5, min(5.5, round(4.2 * h / 900, 2))),
      ann_rel_height = max(2.0, min(4.5, round(3.2 * h / 900, 2)))
    )
  }
  
  # Null-safe accessor: returns "nhanes" if input$corr_setting is NULL (on startup)
  get_corr_setting <- function() {
    if (is.null(input$corr_setting) || length(input$corr_setting) == 0)
      "nhanes"
    else
      input$corr_setting
  }
  
  # Wide plot (win_width >= 900) - all 8 methods, all 3 scenarios
  tile_plot <- eventReactive(list(input$update, input$corr_setting), {
    withProgress(message = "Building tile plot...", value = 0.1, {
      ap <- get_ann_params()
      p <- create_tile_plot(
        TPR_mild_group   = input$TPR_mild,
        FPR_mild_group   = input$FPR_mild,
        TPR_medium_group = input$TPR_medium,
        FPR_medium_group = input$FPR_medium,
        TPR_strict_group = input$TPR_strict,
        FPR_strict_group = input$FPR_strict,
        ann_text_size    = ap$ann_size,
        ann_rel_height   = ap$ann_rel_height,
        corr_setting     = get_corr_setting()
      )
      incProgress(0.9)
      p
    })
  }, ignoreNULL = FALSE)
  
  output$tilePlot <- renderPlot({
    req(tile_plot())
    tile_plot()
  },
  res = 80,
  height = function() {
    h <- session$clientData$output_tilePlot_height
    if (is.null(h) || !is.numeric(h) || h < 10) {
      wh <- if (!is.null(input$win_height) && input$win_height > 0) input$win_height else 900
      max(500, wh)
    } else {
      max(500, as.integer(h))
    }
  })
  
  # Narrow plots (win_width < 900) - 9 panels: scenario first, then group
  # Factory: creates an eventReactive for one scenario - group combination.
  # precomp objects are resolved once at factory-call time and captured in the
  # closure; R lexical scoping guarantees each closure holds its own values.
  make_single_plot <- function(scenario, group) {
    precomp_map_nhanes <- list(log03 = precomp_nhanes_log03,
                               log005 = precomp_nhanes_log005,
                               lin   = precomp_nhanes_lin)
    precomp_map_nocorr <- list(log03 = precomp_nocorr_log03,
                               log005 = precomp_nocorr_log005,
                               lin   = precomp_nocorr_lin)
    eventReactive(list(input$update, input$corr_setting), {
      pc <- if (get_corr_setting() == "none")
        precomp_map_nocorr[[scenario]]
      else
        precomp_map_nhanes[[scenario]]
      withProgress(message = paste0("Building ", scenario, "/", group, "\u2026"),
                   value = 0.1, {
                     ap <- get_ann_params()
                     p <- create_tile_single(
                       precomp          = pc,
                       group            = group,
                       TPR_mild_group   = input$TPR_mild,
                       FPR_mild_group   = input$FPR_mild,
                       TPR_medium_group = input$TPR_medium,
                       FPR_medium_group = input$FPR_medium,
                       TPR_strict_group = input$TPR_strict,
                       FPR_strict_group = input$FPR_strict,
                       ann_text_size    = ap$ann_size,
                       ann_rel_height   = ap$ann_rel_height,
                       corr_setting     = input$corr_setting
                     )
                     incProgress(0.9)
                     p
                   })
    }, ignoreNULL = FALSE)
  }
  
  # Height helper: falls back to proportional win_height when output is hidden.
  # log005 has 4 EPV rows (~28% of height); log03 and lin have 8 rows (~38%).
  single_height <- function(output_id, scenario) {
    function() {
      h <- session$clientData[[paste0("output_", output_id, "_height")]]
      if (is.null(h) || !is.numeric(h) || h < 10) {
        wh <- if (!is.null(input$win_height) && input$win_height > 0)
          input$win_height else 900
        frac <- if (scenario == "log005") 0.28 else 0.38
        max(200, round(wh * frac))
      } else {
        max(200, as.integer(h))
      }
    }
  }
  
  # Create all 9 reactives (scenario-first order)
  tp_lin_mild       <- make_single_plot("lin",    "mild")
  tp_lin_balanced   <- make_single_plot("lin",    "balanced")
  tp_lin_strict     <- make_single_plot("lin",    "strict")
  tp_log03_mild     <- make_single_plot("log03",  "mild")
  tp_log03_balanced <- make_single_plot("log03",  "balanced")
  tp_log03_strict   <- make_single_plot("log03",  "strict")
  tp_log005_mild    <- make_single_plot("log005", "mild")
  tp_log005_balanced <- make_single_plot("log005", "balanced")
  tp_log005_strict  <- make_single_plot("log005", "strict")
  
  # Register all 9 renderPlot outputs
  output$tilePlot_log03_mild <- renderPlot({
    req(tp_log03_mild()); tp_log03_mild()
  }, res = 80, height = single_height("tilePlot_log03_mild", "log03"))
  
  output$tilePlot_log03_balanced <- renderPlot({
    req(tp_log03_balanced()); tp_log03_balanced()
  }, res = 80, height = single_height("tilePlot_log03_balanced", "log03"))
  
  output$tilePlot_log03_strict <- renderPlot({
    req(tp_log03_strict()); tp_log03_strict()
  }, res = 80, height = single_height("tilePlot_log03_strict", "log03"))
  
  output$tilePlot_log005_mild <- renderPlot({
    req(tp_log005_mild()); tp_log005_mild()
  }, res = 80, height = single_height("tilePlot_log005_mild", "log005"))
  
  output$tilePlot_log005_balanced <- renderPlot({
    req(tp_log005_balanced()); tp_log005_balanced()
  }, res = 80, height = single_height("tilePlot_log005_balanced", "log005"))
  
  output$tilePlot_log005_strict <- renderPlot({
    req(tp_log005_strict()); tp_log005_strict()
  }, res = 80, height = single_height("tilePlot_log005_strict", "log005"))
  
  output$tilePlot_lin_mild <- renderPlot({
    req(tp_lin_mild()); tp_lin_mild()
  }, res = 80, height = single_height("tilePlot_lin_mild", "lin"))
  
  output$tilePlot_lin_balanced <- renderPlot({
    req(tp_lin_balanced()); tp_lin_balanced()
  }, res = 80, height = single_height("tilePlot_lin_balanced", "lin"))
  
  output$tilePlot_lin_strict <- renderPlot({
    req(tp_lin_strict()); tp_lin_strict()
  }, res = 80, height = single_height("tilePlot_lin_strict", "lin"))
  
}

#####################################################################################
# RUN
#####################################################################################

# Make the local 'figure/' subfolder accessible to the browser.
# Shiny only serves files from 'www/' by default; this maps the URL path
# '/figure/' to the local 'figure/' directory next to the app file.
#addResourcePath("figure", "figure")

shinyApp(ui = ui, server = server)